### PR TITLE
Fix issue #65: Unify error handling and exits between daemon and one-shot modes

### LINKED ISSUE #65: Unify error handling and exits between daemon and one-shot modes
The current implementation mixes std::process::exit inside helper functions with Result-based error propagation, which makes behavior harder to test and reason about.

Requested changes:
- Ensure non-CLI functions like run_daemon and run_once return anyhow::Result<()> instead of calling std::process::exit.
- Restrict std::process::exit to main() only.
- Use structured errors (bail!/anyhow!) for config validation failures instead of eprintln! + exit.

Ref: PR #61 – Implement X.509 certificate fetching in one-shot mode (https://github.com/troydai/spiffe-helper-rust/pull/61).

### PR DESCRIPTION
**Pull request by troydai**
This PR addresses issue #65 by unifying error handling between daemon and one-shot modes.

## Problem

The current implementation mixed `eprintln! + std::process::exit(1)` with `Result`-based error propagation. Additionally, health check server errors were swallowed with `eprintln!` instead of being returned.

## Solution

1. Return `Result` directly from `main()` instead of using `eprintln! + exit`
2. Propagate health check server errors via `tokio::select!` in the daemon loop

## Changes

- **Removed**: `eprintln! + std::process::exit(1)` pattern from `main()`
- **Removed**: All `std::process::exit` calls from the codebase
- **Fixed**: Health check server errors are now propagated to `main()` via the daemon loop's `tokio::select!`, instead of being swallowed

The daemon loop now watches for:
- SIGTERM signals (graceful shutdown)
- Liveness interval ticks
- Health server task completion (indicates failure, propagates error)

## Benefits

- **Idiomatic Rust**: Uses the `Result` return type as intended
- **No swallowed errors**: Health check server failures are properly returned
- **Testability**: Functions can be tested without side effects
- **Consistency**: Uniform error handling across daemon and one-shot modes

## Testing

- All 57 tests pass
- Code compiles without warnings

Closes #65

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -177,26 +169,51 @@ async fn run_daemon(config: config::Config) -> Result<()> {
...
         }
-    }
+    };
 
-    // Shutdown health check server if it was started
-    if let Some(handle) = health_server_handle {
-        handle.abort();
-        println!("Health check server stopped");
+    // Shutdown health check server if it was started and still running
+    if let Some(ref handle) = health_server_handle {
```
Comment (troydai) [inline src/main.rs]: @cursoragent explain this syntax
